server.port: 8080
spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:tcp://localhost/~/test
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: create
  h2:
    database-platform: H2
    console:
      enabled: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 1450441691833129
            client-secret: 0cf8a6c6022b1582f336a2f4b6728444
#Logging
logging:
  level:
    jdbc.sqlonly: OFF
    jdbc.sqltiming: INFO
    jdbc.audit: OFF
    jdbc.resultset: OFF
    jdbc.resultsettable: INFO
    jdbc.connection: INFO